description = "Documentation for the Hugo Ananke theme."

[ananke]
show_recent_posts = false
custom_css = ["fonts.css", "docs-theme.css", "fixes.css", "highlighting.css"]

[ananke.home]
content_alignment = "left" # options: left, center, right

[ananke.pages]
show_date = false

[ananke.social.follow]
networks = ["mastodon"]

[ananke.social.mastodon]
profilelink = "https://mastodon.social/@ananke_theme"
username = "ananke_theme"

[ananke.hooks]
verbosity = "debug" # debug, info, warning, error
