replacements = "github.com/gohugo-ananke/ananke/v2 -> ../../ananke"

[hugoVersion]
extended = false
min = "0.161.0"

[[mounts]]
source = 'node_modules'
target = 'assets'

[[mounts]]
source = 'assets'
target = 'assets'

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/gohugo-ananke/ananke/v2'
